AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  garden-photographer
  
  Sample SAM Template for garden-photographer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  GetPhotosFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: getPhotos/
      Handler: getPhotos
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /photos
            Method: GET
      Policies:
        - AmazonS3ReadOnlyAccess

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetPhotosAPI:
    Description: "API Gateway endpoint URL for Prod environment for getting photos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/photos"
  GetPhotosFunction:
    Description: "Get Photos Function ARN"
    Value: !GetAtt GetPhotosFunction.Arn
  GetPhotosFunctionIamRole:
    Description: "Implicit IAM Role created for Get Photos function"
    Value: !GetAtt GetPhotosFunctionRole.Arn
